[package]
name = "napcat-qq-client"
edition.workspace = true
publish = false
authors = ["NapCatQQ-RS"]

[dependencies]
async-trait = "0.1"
serde = { workspace = true }
tokio.workspace = true
thiserror.workspace = true

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
