[package]
name = "napcat-cli"
version = "0.1.0"
edition.workspace = true
publish = false

authors = ["NapCatQQ-RS"]

[dependencies]
clap.workspace = true
tokio.workspace = true
napcat-api = { path = "../api" }
napcat-config = { path = "../config" }
napcat-protocol = { path = "../protocol" }
napcat-qq-client = { path = "../qq-client" }
